Handle get token errors
resuelve/wax pull request #66
Opened 2023-06-09 21:01 UTC by LaErika

Se maneja errores al solicitar token

2023-06-15 15:47 UTC, MisaelRaLo approved these changes

2023-06-26 23:12 UTC, MisaelRaLo requested changes

2023-06-26 23:12 UTC, MisaelRaLo commented on lib/auth/manager.ex
> +        {:error, "Error fetching credentials"}
Podemos actualizar el `spec` de esta funcion? Con algo como:
`{:ok, map()} | {:error, "Error fetching credentials"}`
 Ya que ahora regresa una tupla y no un mapa

2023-06-26 23:12 UTC, MisaelRaLo commented on lib/auth/server.ex
> +  @five_minute 5 * 60 * 1_000
```suggestion
  @five_minutes 5 * 60 * 1_000
```

2023-06-26 23:12 UTC, MisaelRaLo commented on lib/auth/server.ex
> +      end)
Podemos refactorizar esto para evitar `IF` anidados y que el código sea más legible, algo como:

    Logger.info("Updating tokens")
    result =
      Enum.reduce(providers, %{}, fn provider, providers_tokens_data ->
        with %{} = token_data <- Map.get(stored_tokens, provider.name),
          expires <- Map.get(token_data, "expires_after"),
          false <- token_expired?(expires) do
            Map.put(providers_tokens_data, provider.name, token_data)
        else
          _ -> Token.renew(provider, providers_tokens_data)
        end
      end)
      
      defp token_expired?(expires) do
        hours_diff = (expires && Timex.diff(expires, Timex.now(), :hours)) || 0
        hours_diff < 24
      end

2023-06-26 23:35 UTC, LaErika commented on lib/api/contacts.ex
>    @spec check_list(tuple(), [String.t()], boolean) :: map
Lo deje en la funcion que recibe los parametros para tener mayor visibilidad, las dos funciones anteriores son comodines

2023-06-27 13:50 UTC, MisaelRaLo approved these changes

2023-06-27 17:28 UTC, devonmx approved these changes
LGTM

2023-06-27 18:24 UTC, merged